/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function readFile(path: string): Array<number>
export declare function outPutFile(path: string, data: Array<number>): void
